apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdashboard
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webdashboard
        image: stefan001/service-mesh:webdashboard
---
apiVersion: v1
kind: Service
metadata:
  name: webdashboard-service
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
  ports:
    - name: http
      port: 3000
      nodePort: 31515
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
spec:
  selector:
    matchLabels:
      app: sensor
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: sensor
    spec:
      containers:
      - name: sensor
        image: stefan001/service-meshv2:sensor
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sensor
spec:
  selector:
    app: sensor
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  selector:
    matchLabels:
      app: data
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefan001/service-meshv2:data
        env:
        - name: INFLUXDB_HOST
          value: influxdb
        - name: INFLUXDB_PORT
          value: '8086'
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data
spec:
  selector:
    app: data
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: stefan001/service-meshv2:analytics
        env:
        - name: INFLUXDB_HOST
          value: influxdb
        - name: INFLUXDB_PORT
          value: '8086'
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - name: http
      port: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command
spec:
  selector:
    matchLabels:
      app: command
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: command
    spec:
      containers:
      - name: command
        image: stefan001/service-meshv2:command
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: command
spec:
  selector:
    app: command
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: stefan001/service-meshv2:gateway
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siddhi
spec:
  selector:
    matchLabels:
      app: siddhi
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: siddhi
    spec:
      containers:
      - name: siddhi
        image: stefan001/service-mesh:siddhi
---
apiVersion: v1
kind: Service
metadata:
  name: siddhi
spec:
  selector:
    app: siddhi
  ports:
    - name: http
      port: 8006
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
spec:
  selector:
    matchLabels:
      app: mqtt
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto:1.6.12
        ports:
        - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  selector:
    app: mqtt
  ports:
    - name: mqtt 
      port: 1883
      targetPort: 1883
      protocol: TCP 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influx-db
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: influx-db
    spec:
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
      containers:
      - name: influxdb
        image: influxdb:1.8.10
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influx.db
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
  app: influx-db
  ports:
    - name: influxdb 
      port: 8086
      targetPort: 8086
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-main
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:1.4.0
---
apiVersion: v1
kind: Service
metadata:
  name: nats-main
spec:
  selector:
    app: nats
  ports:
    - name: http
      port: 4222
  type: ClusterIP
---